stages:
  - upload

.upload:
  stage: upload
  image: alpine:latest
  script:
    - apk add python3
    - apk add py3-requests
    - apk add helm
    - python3 build_and_upload.py

upload-test:
  extends:
    - .upload
  variables:
    USER: $TEST_USER
    PASS: $TEST_PASS
    REPO_URL: $TEST_REPO_URL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

upload-stable:
  extends:
    - .upload
  variables:
    USER: $STABLE_USER
    PASS: $STABLE_PASS
    REPO_URL: $STABLE_REPO_URL
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
