stages:
  - upload

.parallel:
  parallel:
    matrix:
      - CHART: [wireguard, transmission-vpn, aircraft-tracker, ping, ingressroute] 

.upload:
  stage: upload
  image: raackley/gitlab-runner:latest
  script:
    - helm dependency update charts/${CHART}/
    - helm cm-push charts/${CHART}/ $REPO_URL -f -u $USER -p $PASS
  parallel: !reference [.parallel,parallel]

upload-test:
  extends:
    - .upload
  variables:
    USER: $TEST_USER
    PASS: $TEST_PASS
    REPO_URL: $TEST_REPO_URL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

upload-stable:
  extends:
    - .upload
  variables:
    USER: $STABLE_USER
    PASS: $STABLE_PASS
    REPO_URL: $STABLE_REPO_URL
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
