---
apiVersion: v2
appVersion: 1.32.0.6973-a787c5a8e-ls164
description: Plex Media Server
name: plex
version: 11.0.5
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.2.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        Updated library version to 1.2.0.
      links:
        - name: Common library chart definition
          url: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/Chart.yaml
