{{- $fullName := include "wireguard.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
  - name: wireguard
    port: 51820
    nodePort: 31820
    protocol: UDP
