apiVersion: v1
kind: Service
metadata:
  name: fr24feed-service
spec:
  type: NodePort
  selector:
    app: fr24feed
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8754
      targetPort: 8754
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31754