apiVersion: v1
kind: Service
metadata:
  name: fr24feed-service
spec:
  type: ClusterIP
  selector:
    app: fr24feed
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8754
      targetPort: 8754