apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr24feed
  labels:
    app: fr24feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fr24feed
  template:
    metadata:
      labels:
        app: fr24feed
    spec:
      containers:
      - name: fr24feed
        image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest
        env:
        - name: TZ
          value: {{ .Values.timezone | quote }}
        - name: BEASTHOST
          value: {{ .Values.beast.host | quote }}
        - name: MLAT
          value: {{ .Values.fr24feed.mlat | quote }}
        - name: FR24KEY
          value: {{ .Values.fr24feed.key | quote }}
        ports:
        - containerPort: 8754