---
apiVersion: v2
appVersion: v2.17.39 # https://hub.docker.com/r/semaphoreui/semaphore/tags
description: Anisible-Semaphore
name: semaphore
version: 0.2.8
dependencies:
  - name: common
    version: 1.5.1
    repository: https://bjw-s-labs.github.io/helm-charts/
