---
apiVersion: v2
appVersion: v2.12.17 # https://hub.docker.com/r/semaphoreui/semaphore/tags
description: Anisible-Semaphore
name: semaphore
version: 0.2.6
dependencies:
  - name: common
    version: 1.5.1
    repository: https://bjw-s.github.io/helm-charts/
