image:
  pullPolicy: IfNotPresent
  repository: semaphoreui/semaphore
  tag: ""

env:
  SEMAPHORE_DB_DIALECT: bolt
  SEMAPHORE_ADMIN_PASSWORD: changeme #initial install only
  SEMAPHORE_ADMIN_NAME: admin
  SEMAPHORE_ADMIN_EMAIL: admin@localhost
  SEMAPHORE_ADMIN: admin

initContainers:
  volume-permissions:
    image: busybox
    command: ['sh', '-c', 'chown -R 1001 /var/lib/semaphore/']
    volumeMounts:
      - name: db
        mountPath: /var/lib/semaphore/

service:
  main:
    ports:
      http:
        port: 3000
        protocol: TCP
        targetPort: 3000

probes:
  liveness:
    enabled: true
    type: "HTTP"
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  db:
    enabled: true
    mountPath: /var/lib/semaphore/
    accessMode: ReadWriteOnce
    size: 1Gi

ingress:
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              port: http
