image:
  pullPolicy: IfNotPresent
  repository: semaphoreui/semaphore
  tag: ""

env:
  SEMAPHORE_DB_DIALECT: bolt
  SEMAPHORE_DB_HOST: /home/semaphore/database.boltdb
  SEMAPHORE_ADMIN_PASSWORD: changeme #initial install only
  SEMAPHORE_ADMIN_NAME: admin
  SEMAPHORE_ADMIN_EMAIL: admin@localhost
  SEMAPHORE_ADMIN: admin
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU= #change this: head -c32 /dev/urandom | base64

initContainers:
  volume-permissions:
    image: busybox
    command: ['sh', '-c', 'chown -R 1001 /home/semaphore/']
    volumeMounts:
      - name: home
        mountPath: /home/semaphore/

service:
  main:
    ports:
      http:
        port: 3000
        protocol: TCP
        targetPort: 3000

probes:
  liveness:
    enabled: true
    type: "HTTP"
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  home:
    enabled: true
    mountPath: /home/semaphore/
    accessMode: ReadWriteOnce
    size: 1Gi

resources:
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              port: http
