apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "transmission-vpn.fullname" . }}-data"
  labels:
    {{- include "transmission-vpn.selectorLabels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
{{ toYaml .Values.persistence.data.accessModes | indent 4 }}
{{- if .Values.persistence.data.storageClass }}
{{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.data.size }}"