apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission-vpn.fullname" . }}
  labels:
    {{- include "transmission-vpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "transmission-vpn.selectorLabels" . | nindent 4 }}