---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "template.fullname" . }}-mongodb-init-js
data:
  init-mongo.js: |
    db.getSiblingDB("{{ .Values.mongodb.dbname }}").createUser({
      user: "{{ .Values.mongodb.username }}",
      pwd: "{{ .Values.mongodb.password}}",
      roles: [
       {role: "dbOwner", db: "{{ .Values.mongodb.dbname}}"},
       {role: "dbOwner", db: "{{ .Values.mongodb.dbname_stat}}"},
       {role: "dbOwner", db: "{{ .Values.mongodb.dbname_audit}}"},
       {role: "readWrite", db: "{{ .Values.mongodb.dbname }}"}
    ]});
    db.getSiblingDB("{{ .Values.mongodb.dbname_stat}}").createUser({
      user: "{{ .Values.mongodb.username }}",
      pwd: "{{ .Values.mongodb.password}}",
      roles: [
        {role: "dbOwner", db: "{{ .Values.mongodb.dbname_stat}}"},
        {role: "readWrite", db: "{{ .Values.mongodb.dbname_stat}}"}
    ]});
    db.getSiblingDB("{{ .Values.mongodb.dbname_audit}}").createUser({
      user: "{{ .Values.mongodb.username }}",
      pwd: "{{ .Values.mongodb.password}}",
      roles: [
        {role: "dbOwner", db: "{{ .Values.mongodb.dbname_audit}}"},
        {role: "readWrite", db: "{{ .Values.mongodb.dbname_audit}}"}
    ]});
