controllers:
  main:
    replicas: 1
    strategy: Recreate
    containers:
      main:
        image:
          pullPolicy: Always
          repository: ghcr.io/raackley/meshcommander
          tag: "{{.Chart.AppVersion}}"

service:
  main:
    ports:
      http:
        port: 3000
        targetPort: 3000

ingress:
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
