---
apiVersion: v2
appVersion: latest # https://fleet.linuxserver.io/image?name=linuxserver/radarr
description: Radarr
name: radarr
version: 1.0.0
dependencies:
  - name: common
    version: 1.5.0
    repository: https://bjw-s.github.io/helm-charts/
