defaultPodOptions:
  securityContext:
    runAsGroup: 0
    runAsUser: 0

controllers:
  main:
    replicas: 1
    strategy: RollingUpdate
    containers:
      main:
        image:
          pullPolicy: IfNotPresent
          repository: searxng/searxng
          tag: "{{.Chart.AppVersion}}"
        env:
          BASE_URL: ""
          INSTANCE_NAME: SearXNG
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false

service:
  main:
    ports:
      http:
        port: 8080
        targetPort: 8080

persistence:
  config:
    enabled: false
    size: 1Gi
    globalMounts:
      - path: /etc/searxng
        readOnly: false

ingress:
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
