controllers:
  main:
    replicas: 1
    containers:
      main:
        image:
          pullPolicy: Always
          repository: dreista/vlmcsd
          tag: latest

service:
  main:
    ports:
      http:
        port: 1688
        targetPort: 1688

ingress:
  main:
    enabled: false
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
